### ISSUE TITLE
Error in Perform propagation inside a given connected component

### ISSUE THREAD

**Issue by anani-a-missinou** [computational-chemical-biology/ChemWalker#2]
Hi dear developper, 

I try to use your pipeline to propagate metabolic networks. By at the step of "Perform propagation inside a given connected component" I get an error.

![image](https://user-images.githubusercontent.com/45430190/233792107-a853542e-942a-4c69-8c67-23200d443b85.png)

Please, can you help me to solve the error

**Comment by ridasilva** [comment]
@tiagocabralborelli, please help the user.

**Comment by tiagocabralborelli** [comment]
Hi, @anani-a-missinou. Thanks for using Chemwalker. I gonna try to repruduce this error to solve it. Did you used your own GNPS job id or just trayed with ours? Can you provid it to me?

Here are a possible explanation:  base in the returned messege  "component with 0 node" I think you forgot to pass the component index of the cluster that you want to propagate. Check the table called net to see what component index (cluster of nodes) you node (CLUSTERID1 ou CLUSTERID2 ) belongs to.  Then pass it to the parameter __comp_index__ in the function __walk_comp_index__ 

To propagate information, chemwalker needs at least a known node. 

Please update me when your try again.

**Comment by anani-a-missinou** [comment]
Hi Tiago, 

Sorry for too late response.

I try with my own id=0da29a762fa74751a9e0afc6f2b8efeb. Thank you for this useful explanation.

Also, I use the code basic_use_colab.ipynb. Now I try to reproduce this error, but I can't. 

So I retry to use exactly our code and our id, but it doesn't work

Thank you for your help.

![image](https://github.com/computational-chemical-biology/ChemWalker/assets/45430190/b218511d-eae6-4df1-b1c5-3273b8279cec)
