### ISSUE TITLE
[ChemWalker] chemwalker_nextflow_workflow in GNPS2 failed with default COCONUT DB

### ISSUE THREAD

**Issue by amcaraballor** [computational-chemical-biology/ChemWalker#6]
The classical molecular network was obtained from classical_networking_workflow in GNPS2 

GNPS2 TaskID to use: 69777aa026ac455988033599da083f35
Link to GNPS2 Classical MN: https://gnps2.org/status?task=69777aa026ac455988033599da083f35
Errors: 
Component with 2 nodes An exception occurred: Mismatch between spectra and attributes.
Command error:
  [10:03:09] Invalid InChI prefix in generating InChI Key
  
Link to failed chemwalker_nextflow_workflow job in GNPS2 : https://gnps2.org/status?task=ccb097c3104a49fbae8df38b07f33856

**Comment by ridasilva** [comment]
Hi @albertogilf I just pushed a change to try to solve this issue. The library tests are ok, but I would like to test this in production because this network is too large. Is it going to production automatically?

**Comment by ridasilva** [comment]
The issue seems to be a matter of processing power/memory. Individual molecular families can be processed, see the example for ComponentIndex 25
https://gnps2.org/status?task=fc5abf74a3d24457acfafa890c7f7f57
